### ISSUE TITLE
请教一下api是如何使用的呢

### ISSUE THREAD

**Issue by candies404** [lilac-milena/Magic-Link#7]
在相关文档中没用找到说明

**Comment by lilac-milena** [comment]
收到
马上开始写 API 文档，大概 2 小时左右，
本来想着写来着。后来忙忘了，
谢谢。

**Comment by candies404** [comment]
非常感谢

**Comment by lilac-milena** [comment]
抱歉久等啦
文档已经写完了，在 https://github.com/lilac-milena/Magic-Link/blob/main/API-documentation.zh.md 您可以看看，
有不明白的随时问我就好，如果有更好的写法也欢迎提 Commit。
看文档之前记得要**先重新拉一遍代码**，因为我为了让 API 鉴权更方便在新版本中改了一部分鉴权逻辑。

祝有美好的一天，
Lilac Milena

**Comment by candies404** [comment]
好的，非常感谢您😀
